name: ecommerce_store
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  equatable:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.13
  http: ^0.13.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/